# ============================================================
# ELISA-2: GDF15 secreted protein vs GDF15 mRNA expression
#
# Purpose:
#   Correlate ELISA-measured secreted GDF15 protein levels
#   normalized to organoid DNA content with GDF15 mRNA expression
#   across paired patient-derived organoid lines.
#
# Maps to:
#   Supplementary Fig. S6
#
# Expected manuscript result:
#   n = 6 paired organoid lines
#   Spearman rho = 0.83, exact P = 0.058
#
# Input data:
#   results/GDF15_ELISA_normalized.xlsx
#     - generated by ELISA-1
#     - required columns: Sample, GDF15_pg_per_ug_DNA
#
#   data/organoid_expression_TPM.xlsx
#     - This file is NOT included in the repository because the underlying
#       patient-derived organoid transcriptomic data are under controlled
#       access and subject to ethical restrictions.
#     - required sheet: "TPM"
#     - required columns: gene_symbol and one *_TPM column per organoid line
#
# Group labels:
#   "DM" = tumor-associated diabetes (TAD)
#   "Normal" = non-TAD
#
# Notes:
#   Spearman exact P value is used because this is a small exploratory
#   paired analysis. The script checks for ties before running the exact test.
# ============================================================

suppressPackageStartupMessages({
  library(readxl)
  library(dplyr)
})

# ---- Paths ----
protein_file <- "results/GDF15_ELISA_normalized.xlsx"
tpm_file     <- "data/organoid_expression_TPM.xlsx"
tpm_sheet    <- "TPM"

stopifnot(file.exists(protein_file))
stopifnot(file.exists(tpm_file))

# ---- Group assignment ----
dm_cases <- c("KYK019", "KYK020", "KYK067", "KYK084", "KYK090", "KYK093")

# ---- Load ELISA protein output ----
protein <- read_excel(protein_file) %>%
  transmute(
    SampleID = sub("_.*", "", Sample),
    GDF15_pg_per_ug_DNA = GDF15_pg_per_ug_DNA
  )

# ---- Load TPM expression matrix ----
tpm <- read_excel(tpm_file, sheet = tpm_sheet)

stopifnot("gene_symbol" %in% colnames(tpm))

tpm_cols <- grep("_TPM$", colnames(tpm), value = TRUE)
stopifnot(length(tpm_cols) > 0)

gdf15_row <- tpm %>%
  filter(gene_symbol == "GDF15")

stopifnot(nrow(gdf15_row) >= 1)

# ---- Extract GDF15 mRNA expression ----
mrna <- data.frame(
  Sample = tpm_cols,
  GDF15_log2TPM = log2(as.numeric(gdf15_row[1, tpm_cols]) + 1),
  stringsAsFactors = FALSE
) %>%
  mutate(
    SampleID = sub("_.*", "", Sample)
  ) %>%
  group_by(SampleID) %>%
  summarise(
    GDF15_log2TPM = mean(GDF15_log2TPM, na.rm = TRUE),
    .groups = "drop"
  )

# ---- Merge paired protein and mRNA data ----
dat <- inner_join(protein, mrna, by = "SampleID") %>%
  filter(
    !is.na(GDF15_pg_per_ug_DNA),
    !is.na(GDF15_log2TPM)
  ) %>%
  mutate(
    Group = ifelse(SampleID %in% dm_cases, "DM", "Normal")
  )

cat("Paired samples:", nrow(dat), "\n")
cat("Group counts:\n")
print(table(dat$Group))

print(dat)

# ---- Check expected sample size ----
if (nrow(dat) != 6) {
  warning("The number of paired samples is not 6. Check SampleID matching.")
}

# ---- Check for ties before exact Spearman test ----
has_ties <- function(x) {
  any(duplicated(x[!is.na(x)]))
}

if (has_ties(dat$GDF15_pg_per_ug_DNA) || has_ties(dat$GDF15_log2TPM)) {
  stop(
    "Ties were detected. Exact Spearman P value cannot be computed reliably. ",
    "Check the input data or use exact = FALSE and update the manuscript accordingly."
  )
}

# ---- Spearman rank correlation ----
rho <- cor.test(
  dat$GDF15_pg_per_ug_DNA,
  dat$GDF15_log2TPM,
  method = "spearman",
  exact = TRUE
)

cat("\nSpearman correlation:\n")
print(rho)

# ---- Save results ----
dir.create("results", showWarnings = FALSE)

write.csv(
  dat,
  "results/ELISA_GDF15_protein_mRNA_paired_data.csv",
  row.names = FALSE
)

sink("results/ELISA_GDF15_protein_mRNA_correlation.txt")
cat("Paired samples:", nrow(dat), "\n\n")
cat("Group counts:\n")
print(table(dat$Group))
cat("\nPaired data:\n")
print(dat)
cat("\nSpearman correlation:\n")
print(rho)
cat("\nSession info:\n")
sessionInfo()
sink()
